[core]
parse_dot_files = false
file_tags_propagation = true
ignored = []
# default vault paths when none is provided
vault_paths = [
  # "./test-vault",
]
use_american_format = true
indent_length = 2
tracker_extra_blanks = 3

[display]
show_relative_due_dates = true

[pretty_symbols]
task_done = "âœ…"
task_todo = "âŒ"
task_incomplete = "â³"
task_canceled = "ğŸš«"
due_date = "ğŸ“…"
priority = "â—"
today_tag = "â˜€ï¸"
progress_bar_true = "ğŸŸ©"
progress_bar_false = "â¬œï¸"

[task_state_markers]
todo = ' '
done = 'x'
incomplete = '/'
canceled = '-'

# Nice if your terminal font doesn't have emojis
# task_done="[x]"
# task_todo="[ ]"
# task_incomplete="[/]"
# task_canceled="[-]"
# due_date="@"
# priority="!"
# today_tag="+"
# progress_bar_true="="
# progress_bar_false=" "
