use_american_format = true
show_relative_due_dates = true
indent_length = 2
parse_dot_files = false
file_tags_propagation = true
ignored = []
# vault_path= "./test-vault" # default vault path when none is provided
explorer_default_search_string = "- [ ] "
filter_default_search_string = ""
invert_tracker_entries = true
completion_bar_length = 5
tracker_extra_blanks = 3

[task_state_markers]
todo = ' '
done = 'x'
incomplete = '/'
canceled = '-'

[pretty_symbols]
task_done = "âœ…"
task_todo = "âŒ"
task_incomplete = "â³"
task_canceled = "ğŸš«"
due_date = "ğŸ“…"
priority = "â—"
today_tag = "â˜€ï¸"
progress_bar_true = "ğŸŸ©"
progress_bar_false = "â¬œï¸"

# Nice if your terminal font doesn't have emojis
# task_done="[x]"
# task_todo="[ ]"
# task_incomplete="[/]"
# task_canceled="[-]"
# due_date="@"
# priority="!"
# today_tag="+"
# progress_bar_true="="
# progress_bar_false=" "


